version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules:cached
    ports:
      - 5000:3000
    restart: always
    depends_on:
      - database
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
  # The Database
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbdata:/var/lib/mysql:cached
    env_file:
      - ./.env
    ports:
      - 33061:3306
volumes:
  node_modules:
  dbdata:
