version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules:cached
    ports:
      - 5000:3000
    restart: always
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
volumes:
  node_modules:
